FROM rust:latest AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin cs-orchestrator

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/cs-orchestrator /app/
CMD ["./cs-orchestrator"]
