version: '3.8'
services:
  cs-orchestrator:
    image: chrono-swarm/cs-orchestrator:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8080:8080"
    depends_on:
      - cs-api
      - cs-scheduler
      - cs-reconciler
      - cs-spawner
      - cs-watchdog
  cs-api:
    image: chrono-swarm/cs-api:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8081:8081"
  cs-scheduler:
    image: chrono-swarm/cs-scheduler:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8082:8082"
  cs-reconciler:
    image: chrono-swarm/cs-reconciler:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8083:8083"
  cs-spawner:
    image: chrono-swarm/cs-spawner:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8084:8084"
  cs-watchdog:
    image: chrono-swarm/cs-watchdog:test
    environment:
      - RUST_LOG=debug
    ports:
      - "8085:8085"
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=chrono
      - POSTGRES_PASSWORD=swarm
      - POSTGRES_DB=chrono
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:3.4
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
networks:
  default:
    driver: bridge
