name: Deploy Production
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PROD_DEPLOY_KEY }}
      - name: Deploy with Ansible
        run: ansible-playbook -i ansible/inventories/production ansible/playbooks/site.yml
      - name: Terraform Apply
        run: terraform -chdir=terraform/environments/production apply -auto-approve
      - name: Docker Compose Up
        run: docker-compose -f deployment/docker/docker-compose.yml up -d
