name: Security Audit
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Audit
        run: cargo audit || true
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
      - name: Terraform Scan
        run: terraform -chdir=terraform/environments/production validate
      - name: Ansible Lint
        run: ansible-lint ansible/playbooks/
